bt_navigator:
  ros__parameters:
    use_sim_time: False
    global_frame: map
    robot_base_frame: base_link
    odom_topic: /odom
    default_bt_xml_filename: "navigate_w_replanning_and_recovery.xml"
    default_nav_to_pose_bt_xml: "/userdata/novabot_slam/install/coverage_planner/share/coverage_planner/behavior_trees/navigate_to_pose_w_replanning_and_recovery.xml"
    bt_loop_duration: 25
    default_server_timeout: 50
    enable_groot_monitoring: False
    groot_zmq_publisher_port: 1666
    groot_zmq_server_port: 1667
    plugin_lib_names:
      - nav2_compute_path_to_pose_action_bt_node
      - nav2_compute_path_through_poses_action_bt_node
      - nav2_follow_path_action_bt_node
      - nav2_back_up_action_bt_node
      - nav2_spin_action_bt_node
      - nav2_wait_action_bt_node
      - nav2_clear_costmap_service_bt_node
      - nav2_is_stuck_condition_bt_node
      - nav2_goal_reached_condition_bt_node
      - nav2_goal_updated_condition_bt_node
      - nav2_initial_pose_received_condition_bt_node
      - nav2_reinitialize_global_localization_service_bt_node
      - nav2_rate_controller_bt_node
      - nav2_distance_controller_bt_node
      - nav2_speed_controller_bt_node
      - nav2_truncate_path_action_bt_node
      - nav2_goal_updater_node_bt_node
      - nav2_recovery_node_bt_node
      - nav2_pipeline_sequence_bt_node
      - nav2_round_robin_node_bt_node
      - nav2_transform_available_condition_bt_node
      - nav2_time_expired_condition_bt_node
      - nav2_distance_traveled_condition_bt_node
      - nav2_single_trigger_bt_node
      - nav2_is_battery_low_condition_bt_node
      - nav2_navigate_through_poses_action_bt_node
      - nav2_navigate_to_pose_action_bt_node
      - nav2_remove_passed_goals_action_bt_node
      - nav2_planner_selector_bt_node
      - nav2_controller_selector_bt_node
      - nav2_goal_checker_selector_bt_node

bt_navigator_rclcpp_node:
  ros__parameters:
    use_sim_time: False

nav2_single_node_navigator:
  ros__parameters:
    use_sim_time: False
    expected_planner_frequency: 1.0
    # GRIDBASED和LINEBASED表示plan_id，通过service指定时可以获取# , "LineBased"
    planner_plugins: [ "GridBased", "LineBased" ]
    GridBased2:
      plugin: "nav2_theta_star_planner/ThetaStarPlanner"
      how_many_corners: 8
      w_euc_cost: 1.0
      w_traversal_cost: 2.0
      w_heuristic_cost: 1.0
    GridBased:
      plugin: 'nav2_navfn_planner/NavfnPlanner'
      tolerance: 0.08
      use_astar: true
      allow_unknown: true
    LineBased:
      plugin: "nav2_straightline_planner/StraightLine"
      tolerance: 0.5
      use_astar: false
      allow_unknown: true
    controller_frequency: 12.0
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.4
    min_theta_velocity_threshold: 0.001
    failure_tolerance: 0.3
    progress_checker_plugin: "progress_checker"
    goal_checker_plugins: ["general_goal_checker", "try_closer_goal_checker" ]
    controller_plugins: [ "FollowPath","FollowPathPurePursuit"]

    # Progress checker parameters
    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.3
      movement_time_allowance: 10.0

    general_goal_checker:
      stateful: True
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.10
      yaw_goal_tolerance: 0.10

    try_closer_goal_checker:
      stateful: True
      plugin: "nav2_controller::TryCloserGoalChecker"
      xy_goal_tolerance: 0.10
      yaw_goal_tolerance: 0.10
      center_ratio: 0.5

    # DWB parameters
    FollowPath:
       plugin: "nav2_rotation_shim_controller::RotationShimController"
       primary_controller: "dwb_core::DWBLocalPlanner"
       angular_dist_threshold: 0.88
       forward_sampling_distance: 0.30
       rotate_to_heading_angular_vel: 1.5
       max_angular_accel: 1.8
       simulate_ahead_time: 1.0
       debug_trajectory_details: False
       min_vel_x: 0.0
       min_vel_y: 0.0
       max_vel_x: 0.35
       max_vel_y: 0.0
       max_vel_theta: 1.17
       min_speed_xy: 0.0
       max_speed_xy: 0.35
       min_speed_theta: 0.0
       # Add high threshold velocity for turtlebot 3 issue.
       # https://github.com/ROBOTIS-GIT/turtlebot3_simulations/issues/75
       acc_lim_x: 2.5
       acc_lim_y: 0.0
       acc_lim_theta: 1.8
       decel_lim_x: -2.0
       decel_lim_y: 0.0
       decel_lim_theta: -1.8
       vx_samples: 15
       vy_samples: 0
       vtheta_samples: 20
       sim_time: 2.0
       linear_granularity: 0.05
       angular_granularity: 0.025
       transform_tolerance: 0.2
       xy_goal_tolerance: 0.07
       trans_stopped_velocity: 0.25
       short_circuit_trajectory_evaluation: True
       stateful: True
       critics: [ "RotateToGoal", "Oscillation", "BaseObstacle", "GoalAlign", "PathAlign", "PathDist", "GoalDist" ]
       BaseObstacle.scale: 0.05
       PathAlign.scale: 32.0
       PathAlign.forward_point_distance: 0.2
       GoalAlign.scale: 24.0
       GoalAlign.forward_point_distance: 0.2
       PathDist.scale: 32.0
       GoalDist.scale: 32.0
       RotateToGoal.scale: 32.0
       RotateToGoal.slowing_factor: 3.0
       RotateToGoal.lookahead_time: -1.0
#      #  teb----------------------
#      plugin: "teb_local_planner::TebLocalPlannerROS"
#      footprint_model.type: circular
#      footprint_model.radius: 0.17
#      min_obstacle_dist: 0.1
#      inflation_dist: 0.1
#      ## disable costmap converter, will reduce cpu cost 50%
#      costmap_converter_plugin: "debug-costmap_converter::CostmapToPolygonsDBSMCCH"
#      costmap_converter_spin_thread: False
#      costmap_converter_rate: 2
#      enable_homotopy_class_planning: False
#      enable_multithreading: False
#      optimization_verbose: False
#      teb_autoresize: True
#      min_samples: 3
#      max_samples: 15
#      max_global_plan_lookahead_dist: 1.0
#      visualize_hc_graph: False
#      max_vel_x: 0.36
#      max_vel_theta: 1.574
#      acc_lim_x: 2.5
#      acc_lim_theta: 0.1
#      dt_ref: 0.25
#      dt_hysteresis: 0.15
#      min_turning_radius: 0.0
#      weight_kinematics_forward_drive: 1000.0
#      weight_viapoint: 100.0
#      global_plan_viapoint_sep: 0.2
#      yaw_goal_tolerance: 0.3
#      max_global_plan_lookahead_dist: 1.2
#      global_plan_overwrite_orientation: True
#      publish_feedback: False
#      wheelbase: 0.4
#      no_inner_iterations: 2
#      no_outer_iterations: 2
#      global_plan_prune_distance: 0.6
    FollowPathPurePursuit:
      plugin: "nav2_rotation_shim_controller::RotationShimController"
      primary_controller: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
      angular_dist_threshold: 0.1745
      forward_sampling_distance: 0.50
      rotate_to_heading_angular_vel: 1.0
      max_angular_accel: 1.5
      simulate_ahead_time: 1.0
      debug_trajectory_details: True
      desired_linear_vel: 0.3
      max_linear_accel: 2.0
      max_linear_decel: 2.5
      lookahead_dist: 0.6
      min_lookahead_dist: 0.3
      max_lookahead_dist: 0.9
      lookahead_time: 1.5
      rotate_to_heading_angular_vel: 1.0
      transform_tolerance: 0.1
      use_velocity_scaled_lookahead_dist: false
      min_approach_linear_velocity: 0.05
      use_approach_linear_velocity_scaling: true
      approach_velocity_scaling_dist: 0.10
      max_allowed_time_to_collision: 0.5
      use_regulated_linear_velocity_scaling: true
      use_cost_regulated_linear_velocity_scaling: false
      regulated_linear_scaling_min_radius: 0.9
      regulated_linear_scaling_min_speed: 0.25
      use_rotate_to_heading: true
      rotate_to_heading_min_angle: 0.785
      max_angular_accel: 3.2
      cost_scaling_dist: 0.3
      cost_scaling_gain: 1.0
      inflation_cost_scaling_factor: 3.0

nav2_single_node_navigator_rclcpp_node:
  ros__parameters:
    use_sim_time: False

local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 4.0
      publish_frequency: 2.0
      global_frame: odom
      robot_base_frame: base_link
      use_sim_time: False
      rolling_window: true
      width: 6
      height: 6
      resolution: 0.05
      robot_radius: 0.4
      plugins: [ "obstacle_layer",  "inflation_layer" ]
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 3.0
        inflation_radius: 0.42
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: pointcloud
        pointcloud:
          topic: /tof_filtered_cloud
          min_obstacle_height: 0.20
          max_obstacle_height: 1.0
          clearing: True
          marking: True
          data_type: "PointCloud2"
          raytrace_max_range: 3.0
          raytrace_min_range: 0.50
          obstacle_max_range: 2.2
          obstacle_min_range: 0.05
      static_layer:
        map_subscribe_transient_local: True
      always_send_full_costmap: True
  local_costmap_client:
    ros__parameters:
      use_sim_time: False
  local_costmap_rclcpp_node:
    ros__parameters:
      use_sim_time: False

global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 5.0
      publish_frequency: 1.0
      global_frame: map
      robot_base_frame: base_link
      use_sim_time: True
      robot_radius: 0.4
      resolution: 0.05
      track_unknown_space: true
      plugins: [ "static_layer", "obstacle_layer", "inflation_layer" ]
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: pointcloud
        pointcloud:
          topic: /tof_filtered_cloud
          min_obstacle_height: 0.20
          max_obstacle_height: 1.0
          clearing: True
          marking: True
          data_type: "PointCloud2"
          raytrace_max_range: 3.0
          raytrace_min_range: 0.50
          obstacle_max_range: 2.2
          obstacle_min_range: 0.05
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 3.0
        inflation_radius: 0.42
      always_send_full_costmap: True
  global_costmap_client:
    ros__parameters:
      use_sim_time: False
  global_costmap_rclcpp_node:
    ros__parameters:
      use_sim_time: False

map_server:
  ros__parameters:
    use_sim_time: False
    yaml_filename: "map.yaml"

map_saver:
  ros__parameters:
    use_sim_time: False
    save_map_timeout: 5.0
    free_thresh_default: 0.25
    occupied_thresh_default: 0.65
    map_subscribe_transient_local: True





recoveries_server:
  ros__parameters:
    costmap_topic: local_costmap/costmap_raw
    footprint_topic: local_costmap/published_footprint
    cycle_frequency: 10.0
    recovery_plugins: [ "spin", "backup", "wait" ]
    spin:
      plugin: "nav2_recoveries/Spin"
    backup:
      plugin: "nav2_recoveries/BackUp"
    wait:
      plugin: "nav2_recoveries/Wait"
    global_frame: odom
    robot_base_frame: base_link
    transform_timeout: 0.1
    use_sim_time: true
    simulate_ahead_time: 2.0
    max_rotational_vel: 1.0
    min_rotational_vel: 0.4
    rotational_acc_lim: 3.2

robot_state_publisher:
  ros__parameters:
    use_sim_time: False

waypoint_follower:
  ros__parameters:
    loop_rate: 2000
    stop_on_failure: false
    waypoint_task_executor_plugin: "wait_at_waypoint"
    wait_at_waypoint:
      plugin: "nav2_waypoint_follower::WaitAtWaypoint"
      enabled: True
      waypoint_pause_duration: 200
